# Site Settings
title: Chashm e Afreen
email: example@xyz.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chashm-e-afreen.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
themeColor: "#880e4f"

# User Settings
username: Molten Glass
user_description: Someone who's fascinated by the possibilities of language.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: https://github.com/chashm-e-afreen
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
